config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :records do
  		resources :artists, only: [:show]
  end
  
  root 'records#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
	belongs_to :user
	has_one_attached :art
	validates :title, :artist, :year, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :records, dependent: :destroy
	validates :username, :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :authenticate_user!

	def configure_permitted_parameters
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
	    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
	end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	def show
		@artist_records = Record.all.where(["user_id = ? and artist = ?", current_user.id, params[:id]])
	end

private
	def record_params
    	params.require(:artist).permit(:id, :record_id)
  	end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

	def new
    	@record = Record.new
	end

  	def create
	    @record = Record.create(record_params)
	    @record.user_id = current_user.id
	    if @record.save
	    	redirect_to(@record)
	    else
	    	render :new
	    end
  	end

	def edit
		@record = Record.find(params[:id])
	end

  	def update
	    @record = Record.find(params[:id])
	    if @record.update(record_params)
	    	redirect_to(@record)
	    else
	    	render :edit
	    end
  	end

  	def show
	    @record = Record.find(params[:id])
  	end

  	def index
	    @records = Record.all.where("user_id = ?", current_user.id)
  	end

  	def destroy
	    @record = Record.find(params[:id])
	    if @record.destroy 
	    	redirect_to records_path
	    else
	    	flash[:error] = 'Unable to delete record'
	    end
  	end

private
    def record_params
    	params.require(:record).permit(:user_id, :id, :artist, :title, :year, :condition, :art)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  	def new
  		@user = User.new
  	end

  	def create
	    @user = User.create(user_params)
	    if @user.save
	      redirect_to records_path
	    else
	      flash[:error] = 'Unable to save user profile.'
	      redirect_to new_user_path
	    end
	end

	def edit
	    @user = User.find(current_user.id)
	end

	def update
	    @user = User.find(current_user.id)
	    @user.update(user_params)
	    if @user.save
	      redirect_to user_path(@user)
	    else
	      render :edit
	    end
	end

private
	
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/show.html.erb
Artist History 
<h2><%= @artist_records.first.artist %> </h2>
<%= bar_chart @artist_records.group(:year).count(:id) %>
<h4> <%= link_to "Return to Collection", records_path %> | <%= link_to "Add New Record", new_record_path %></h4>

app/views/layouts/_messages.html.erb
<%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
<%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>

app/views/layouts/_navigation.html.erb
<div class="header">
    <h1 class="logo">Groove</h1>
    <div class="nav">
	    <% if user_signed_in? %>
	    	<ul>
		    	<li> Logged in as <strong><%= current_user.username %></strong> </li>
			    <li> <%= link_to 'Edit profile', edit_user_registration_path%> </li>
			    <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
			</ul>
		<% else %>
			<ul>
		    	<li> <%= link_to "Sign up", new_user_registration_path %> </li>
		    	<li> <%= link_to "Login", new_user_session_path %></li>
		    </ul>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Groove</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Open+Sans|Righteous' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/navigation" %>
    <%= render "layouts/messages" %>
    
    <div class="yield">
      <%= yield %>
    </div>
  </body>
</html>

app/views/records/_form.html.erb
<% if @record.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@record.errors.count, "error") %>
      prohibited this record from being saved:
    </h2>
 
    <ul>
    <% @record.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @record do |f| %>
	<div class="field">
	    <%= f.label :artist %><br />
	    <%= f.text_field :artist %>
    </div>
    <div class="field">
	    <%= f.label :album_title %><br />
	    <%= f.text_field :title %>
    </div>
    <div class="field">
    	<%= f.label :album_art %><br />
    	<%= f.file_field :art %>
    </div>
    <div class="field">
	    <%= f.label :year %><br />
	    <%= f.text_field :year %>
    </div>
    <div class="field">
	    <%= f.label :condition %><br />
	    <%= f.text_field :condition %>
    </div>
    <div class="actions"><%=f.submit%></div>
<% end %>

app/views/records/artist.html.erb
Artist History 
<h2><%= @artist.first.artist %> </h2>
<%= bar_chart @artist.group(:year).count(:id) %>
<h4> <%= link_to "Return to Collection", records_path %> | <%= link_to "Add New Record", new_record_path %></h4>

app/views/records/edit.html.erb
<h1>Update Record</h1>
<%= render "form" %>
<%= link_to "Delete Record", record_path(@record), action: :delete %>

app/views/records/index.html.erb
<h1>Your Record Collection: </h1>
<% if @records.empty? %>
	<h2> You have no records in your collection! Click <%= link_to "here", new_record_path %> to add some. </h2>
<% else %>
	<table>
		<%@records.each do |r| %>
			<tr>
				<td>
					<% if r.art.attached? %>
						<%=image_tag(r.art, size: "80") %>
					<% else %>
						Album art missing
					<% end %>
				</td>
				<td>
					<ul>
						<li>Artist: <%= link_to r.artist, record_artist_path(r.id, r.artist) %> </li> 
						<li> Album Title: <%=r.title %> </li> 
						<li> Album Year: <%=r.year %> </li>
						<li> Album Condition: <%=r.condition %> </li>
					</ul>
				</td>
				<td>
					<ul>
						<li> <%= link_to "View Detail", record_path(r) %> </li>
						<li> <%=link_to "Edit Record", edit_record_path(r) %> </li>
						<li> <%=link_to "Remove Record", record_path(r), method: :delete %> </li>
					</ul>
				</td>
			</tr>
		<% end %>
	</table>
	<%= link_to "Add New Record", new_record_path, class: "add-button" %>
<% end %>

app/views/records/new.html.erb
<h1>Add a Record</h1>
<%= render "form" %>

app/views/records/show.html.erb
<% if @record.art.attached? %>
  <%=image_tag(@record.art, size: "40X40") %>
<% end %>
<h2>
	<ul class="detail">
		<li>Artist: <%= link_to @record.artist, record_artist_path(@record.id, @record.artist) %> </li> 
		<li>Album Title: <%=@record.title %> </li> 
		<li>Album Year: <%=@record.year %> </li>
		<li>Album Condition: <%=@record.condition %> </li>
	</ul> 
</h2> 
<h4> <%= link_to "Return to Collection", records_path %> | <%=link_to "Edit Record", edit_record_path(@record) %> | <%=link_to "Remove Record", record_path(@record), method: :delete %></h4>